### ISSUE TITLE
About the date for codes and model checkpoints releasing

### ISSUE THREAD

**Issue by Trav1slaflame** [Tencent/DepthCrafter#1]
Hi team,

Thanks for your amazing work! I wonder when will the full code and model checkpoints will be releasing? can't wait to try it out.

**Comment by u-can-u-up-no-bb** [comment]
Really cool work! Looking forward to the code and model release!

**Comment by antithing** [comment]
Thanks! Is there any plans for onnx model export so this can be run in c++?

**Comment by loawizard** [comment]
Would love to know when the model releases!

**Comment by donrikk** [comment]
@wbhu very excited for your project currently best we can get atm is blending different maps together but your process here would eliminate the hefty task of exporting 2 seperate depth map sequences from 1 source and manually blending them for use. 

i dont know when it will release, i assume if u have the project page up now that it will be pretty soon so i am looking forward to the release! thanks for your hard work on this! we have entire discord communities awaiting your release so be prepared for a possible influx of people on release 🤣

**Comment by petermg** [comment]
I'm also excited for this to be released.

**Comment by loawizard** [comment]
Donrikk is right. We are all patiently waiting!

**Comment by motypas** [comment]
Great work and non wobbling/flashing depth map. We are wait the code for testing. What we know about the hardware I mean GPU/GPUs requirement?

**Comment by wbhu** [comment]
Hi all,

The code together with a local gradio demo is released now, how fun🔥🔥
