### ISSUE TITLE
Crashes memory on RTX 4090 Laptop (16Go)

### ISSUE THREAD

**Issue by nosy-b** [Tencent/DepthCrafter#10]
Congrats for the great work !
I can't make it run on my laptop with RTX 4090 16Gb with the command 
_python run.py  --video-path examples/example_01.mp4 --max-res 512_, it crashes with memory error.

Is there some other ways to optimize for small configuration?
Thanks!

**Comment by nosy-b** [comment]
It runs with --max-res 256 but is there a way to support higher resolution ? (Even if it 's super slow)
thanks :)

**Comment by redman4585** [comment]
As it currently stands you will need a graphics card with more VRAM than a 4090 (A100) to support the high resolution mode. With further optimizations that won't be necessary.

**Comment by wbhu** [comment]
> It runs with --max-res 256 but is there a way to support higher resolution ? (Even if it 's super slow) thanks :)

Yes, you may feed cpu-offload to be "sequential", which can save a lot of memory, but slow. Refer to https://github.com/Tencent/DepthCrafter/blob/main/run.py#L37
