### ISSUE TITLE
Do you plan to release the  train code?

### ISSUE THREAD

**Issue by QingQingS** [Tencent/DepthCrafter#11]
Hi team,

Thanks for your amazing work! Do you plan to release  the train code ?

**Comment by wbhu** [comment]
thanks for your interest, but we have no plan to release the training code now

**Comment by RenieWell** [comment]
Same here!
It seems that the three stages' training is very important for the performance of DepthCrafter, can you please kindly share the training code?

**Comment by wbhu** [comment]
thanks for your interest, but we have no plan to release the training code now
