### ISSUE TITLE
3D model in the output?

### ISSUE THREAD

**Issue by AbrahamLincoln33** [Tencent/DepthCrafter#12]
hi, can we have 3d reconstruction of input video in the output? like ".glb" files? (like point clouds in your github page)

**Comment by gaoxiangjun** [comment]
We don't conduct 3D recon, just depth estimation. The point clouds are visualized using "viser".

**Comment by gaoxiangjun** [comment]
> @gaoxiangjun is there a code for point cloud generation?

I will upload a demo code for point cloud visualization next few days. Please stay tuned. 
:-)

**Comment by gaoxiangjun** [comment]
@basit-MT Please check [visualization_pcd.py](https://github.com/Tencent/DepthCrafter/blob/main/visualization_pcd.py). 
:-)

**Comment by basit-MT** [comment]
Thanks @gaoxiangjun, works perfectly.

I had another question out of curiosity, do you think fine-tuning DepthCrafter to estimate metric Depth could give useful results? Have tried anything with the metric depth?

**Comment by gaoxiangjun** [comment]
Yeah. It might be possible, but we haven't tried it yet.

**Comment by booker-max** [comment]
> Thanks @gaoxiangjun, works perfectly.
> 
> I had another question out of curiosity, do you think fine-tuning DepthCrafter to estimate metric Depth could give useful results? Have tried anything with the metric depth?

Hello, our goal is also to estimate metric depth. We currently have lidar data and real poses. How can we use depthcrafter to estimate metric depth? Do you have any plans?
