### ISSUE TITLE
the type of depth maps

### ISSUE THREAD

**Issue by haodong2000** [Tencent/DepthCrafter#13]
Hi authors, great work!

I am also working on video depth prediction. And I am wondering is that your predicted depth in disparity space?

That is, 1.0/(depth + tiny value) is the true depth value, same as Depth Anything series.

Thanks!

**Comment by gaoxiangjun** [comment]
We also predict in disparity space. Thanks. :-)

**Comment by Xiang-cd** [comment]
I was wondering, the training process of data just convert the depth space to  the disparity and norm to 0-1 as a gray image?
