### ISSUE TITLE
how to get the point cloud

### ISSUE THREAD

**Issue by feilong234** [Tencent/DepthCrafter#14]
Hey, congrats on the amazing work. Could you provide the pointcloud generation and visualization code using depth infromation for the demo in the github page?  Thanks very much for your kindly help

**Comment by wbhu** [comment]
Thanks for your attention. As unprojecting affine-invariant depth into point clouds is ill-posed, we only provide some examples by manually setting up the camera parameters. Please refer to #12

**Comment by gaoxiangjun** [comment]
Please check the [visualization_pcd.py](https://github.com/Tencent/DepthCrafter/blob/main/visualization_pcd.py). :-)
