### ISSUE TITLE
Image sequence

### ISSUE THREAD

**Issue by pizurny** [Tencent/DepthCrafter#16]
Hello, is it possible to export image sequence instead of compressed mp4?

**Comment by wbhu** [comment]
I think it's definitely doable with only a slight modification at https://github.com/Tencent/DepthCrafter/blob/main/run.py#L101

**Comment by pizurny** [comment]
Thanks for reply, Ive already managed to export 16bit png sequence!

**Comment by pizurny** [comment]
Thanks for reply, Ive already managed to export 16bit png sequence!
