### ISSUE TITLE
和animatediff配合想来是绝配，如果支持comfyui就更棒了。

### ISSUE THREAD

**Issue by daoliangai** [Tencent/DepthCrafter#17]
如果能提供comfyui的支持和fp16大小的模型就更棒了。
中秋快乐！

**Comment by wbhu** [comment]
Thanks for your attention. The provided model is actually in fp16 format. For comfyui, welcome contributions

**Comment by wbhu** [comment]
ComfyUI is available now. Thanks @akatz-ai
