### ISSUE TITLE
如何推理超过110帧的长视频？

### ISSUE THREAD

**Issue by juntaosun** [Tencent/DepthCrafter#18]
目前的 app.py ，只能推理一小段的短视频，约10秒左右。
如何推理长视频，比如几分钟的呢？

我试了分段处理然后拼接，发现深度图视频拼接处的 “闪烁” 非常严重。
后续有计划更新 app.py ，让它支持长视频吗？谢谢~

**Comment by wbhu** [comment]
The default configuration should work for long videos. Would you mind sharing your case to reproduce this?

**Comment by wbhu** [comment]
default value for "process_length" is set to  [195](https://github.com/Tencent/DepthCrafter/blob/main/run.py#L159). If you want to infer a longer video, just feed its value accordingly. For the required GPU memory, you may refer to the information in README

**Comment by wbhu** [comment]
directly concatenating the segments definitely results in flickering, as discussed in our paper (Fig.6). our proposed "Inference for Extremely Long Videos" has been included in the repo.
