### ISSUE TITLE
评估代码

### ISSUE THREAD

**Issue by zhizunhu** [Tencent/DepthCrafter#19]
hello，看到你们放了准备benchmark的脚本，是计划放评估代码吗，如果放的话，大概什么时候ready

**Comment by gaoxiangjun** [comment]
That's just for the evaluation dataset creation.  There is no plan for releasing the full metric evaluation code for now. :-)

**Comment by zhizunhu** [comment]
> That's just for the evaluation dataset creation. There is no plan for releasing the full metric evaluation code for now. :-)

**Comment by gaoxiangjun** [comment]
Has been released now. You may check it. :-)
