### ISSUE TITLE
Specific Cases for Evaluation on Bonn Dataset

### ISSUE THREAD

**Issue by haodong2000** [Tencent/DepthCrafter#2]
Hi authors, great work!

I am curious about the specific cases you selected in Bonn dataset for evaluation. In the paper you said that 5 sequences were selected. Can you tell me which 5 are selected and why these 5 cases are selected?

Thanks,
Haodong

**Comment by gaoxiangjun** [comment]
Hi Haodong,

All the RGBD sequences of the Bonn dataset are captured in the same indoor scene. Moreover, duplicate human identities or very similar movements are within the dataset. We chose 5 cases that are with unique identity or movement.

These are 5 chosen cases: balloon2, crowed2, crowed3, person_tracking2, synchronous.

Thanks,
GAO

**Comment by Junyi42** [comment]
> Hi Haodong,
> 
> All the RGBD sequences of the Bonn dataset are captured in the same indoor scene. Moreover, duplicate human identities or very similar movements are within the dataset. We chose 5 cases that are with unique identity or movement.
> 
> These are 5 chosen cases: balloon2, crowed2, crowed3, person_tracking2, synchronous.
> 
> Thanks, GAO



> Hi Haodong,
> 
> All the RGBD sequences of the Bonn dataset are captured in the same indoor scene. Moreover, duplicate human identities or very similar movements are within the dataset. We chose 5 cases that are with unique identity or movement.
> 
> These are 5 chosen cases: balloon2, crowed2, crowed3, person_tracking2, synchronous.
> 
> Thanks, GAO

Hi @gaoxiangjun , thanks for the great work!

I am wondering how the 110 frames are sampled for these 5 scenes. Are they simply the first 110 frames or sampled of certain strides?

I am also wondering the frames sampled of the 13 Sintel sequences, thanks!

**Comment by gaoxiangjun** [comment]
@Junyi42 We just sampled the first 110 frames for 13 KITTI sequences. Please check our eval dataset conduction scripts uploaded just now for other datasets.
