### ISSUE TITLE
Entry Not Found for config.json

### ISSUE THREAD

**Issue by Theo-SAMINADIN-td** [Tencent/DepthCrafter#20]
Hey guys, I'm having this error - yesterday everything was working perfectly : 

```
huggingface_hub.errors.EntryNotFoundError: 404 Client Error.

Entry Not Found for url: https://huggingface.co/tencent/DepthCrafter/resolve/main/unet/config.json.
```

As it says in the error and when you paste the link, it cannot finds the config.json file, I believe the file has been moved or ? I've seen this [config.json](https://huggingface.co/tencent/DepthCrafter/blob/main/config.json), is that the one it should find ? If so, how can I update the link ?

Any suggestions on how to make this work again ?🙌

**Comment by Theo-SAMINADIN-td** [comment]
I just solved it by downloading the [config.json](https://huggingface.co/tencent/DepthCrafter/blob/main/config.json) and [diffusion_pytorch_model.safetensors](https://huggingface.co/tencent/DepthCrafter/blob/main/diffusion_pytorch_model.safetensors). Then changed, the [unet_path ](https://github.com/Tencent/DepthCrafter/blob/main/run.py#L186)to the config and model folder path.

**Comment by Theo-SAMINADIN-td** [comment]
I just solved it by downloading the [config.json](https://huggingface.co/tencent/DepthCrafter/blob/main/config.json) and [diffusion_pytorch_model.safetensors](https://huggingface.co/tencent/DepthCrafter/blob/main/diffusion_pytorch_model.safetensors). Then changed, the [unet_path ](https://github.com/Tencent/DepthCrafter/blob/main/run.py#L186)to the config and model folder path.

**Comment by wbhu** [comment]
Hi, I update the safetensors location in HF for their standard format. And the github code has been updated accordingly, you may try to pull the latest code
