### ISSUE TITLE
scannet测试数据

### ISSUE THREAD

**Issue by zhizunhu** [Tencent/DepthCrafter#22]
hello，我想问一下论文里是怎么处理的scannet数据集，我看到代码里路径是raw/scans_test，你们是怎么样取得test数据集
<img width="378" alt="截屏2024-09-27 14 26 08" src="https://github.com/user-attachments/assets/708a6393-8479-4331-bf2b-67878ceab496">

**Comment by gaoxiangjun** [comment]
I just downloaded it. The scannet testset is open for downloadin.

**Comment by gaoxiangjun** [comment]
May I ask what gpu did you used ? ;-)

**Comment by zhizunhu** [comment]
Tesla-V100-SXM2-32GB
