### ISSUE TITLE
How to use the prediction result

### ISSUE THREAD

**Issue by sranqiu** [Tencent/DepthCrafter#23]
How to use the prediction result, is the result a disparity map or a depth map?

**Comment by gaoxiangjun** [comment]
That's a disparity map range from [0~1].

**Comment by sranqiu** [comment]
> That's a disparity map range from [0~1].

Thank you for your reply. How can I use the disparity map in the range [0, 1] predicted by the DepthCrafter model in my downstream task without knowing fx, fy, cx, cy?

**Comment by gaoxiangjun** [comment]
You could predefine some intrinsic or make it optimizeable.
