### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by max-sho** [Tencent/DepthCrafter#24]
The code is trying to access the second element of a tuple called frames, but the tuple is empty. It seems like there was a problem loading the video

**Comment by gaoxiangjun** [comment]
Could you show the errors ?

**Comment by Ireneyhy** [comment]
i'm having the same error:
![error](https://github.com/user-attachments/assets/ea809f76-e432-4c9d-81bf-b6e6d361bb4e)

**Comment by gaoxiangjun** [comment]
It seems that it is related to the example video. You can try another video first if you like. I will figure it out later.

**Comment by gaoxiangjun** [comment]
> It seems that it is related to the example video. You can try another video first if you like. I will figure it out later.

I tried it again, and everything worked well. Could you try another video and see whether it works or not ?

**Comment by Ireneyhy** [comment]
i used another video and it was alright.
By the way, the **exmple_01.mp4** video is not openable on my computer. And upon checking metadata it is somehow treated as a .txt (i cloned the repo). But anyway thank you very much.
 File Type                       : TXT
File Type Extension             : txt
MIME Type                       : text/plain
MIME Encoding                   : us-ascii
Newlines                        : Unix LF
Line Count                      : 3
Word Count                      : 6

**Comment by wbhu** [comment]
Hi, this may be because we use git-lfs to host the video files, and it seems the video files were not correctly cloned
