### ISSUE TITLE
background depth

### ISSUE THREAD

**Issue by Davidyao99** [Tencent/DepthCrafter#25]
Great Work!

I am running your model and visualizing the depth on sintel dataset. Since your model outputs normalized disparity, I actually saved the unnormalized disparity (before minusing min and dividing by range), and visualized that in 3D instead. I notice that for some scenes with very distance regions, the unprojected result appears to be a plane. Any idea why this is happening / how to resolve this?

![image](https://github.com/user-attachments/assets/df49589d-d303-46f1-9f94-ae4db58f9f59)
![image](https://github.com/user-attachments/assets/166837b5-cd47-4731-858c-0089d1260e7e)

**Comment by gaoxiangjun** [comment]
Yeah sure. We also noticed that on sintel, it has a problem to estimate the background as far away. It might be related to the training dataset bias. Up to now, we don't how to resolve this. The good news is that the problem only showed in some cases of sintel during our evaluation.

**Comment by Davidyao99** [comment]
I see, ok thanks for the information! The video consistency is still very impressive and works really well on the other videos!
