### ISSUE TITLE
Reproducing benchmark results

### ISSUE THREAD

**Issue by zlai0** [Tencent/DepthCrafter#26]
Hello, thank you for releasing the eval code!

I've been using the benchmark to replicate the results presented in the paper, but I've got some differences in my results.

For instance, on the KITTI dataset, my results are as follows:

abs_relative_difference: 0.143325 (compared to 0.110 in the paper)
rmse_linear: 5.483166
delta1_acc: 0.822513 (compared to 0.881 in the paper)

For Sintel, I got:

abs_relative_difference: 0.343462 (compared to 0.292 in the paper)
rmse_linear: 6.856201
delta1_acc: 0.673080 (compared to 0.697 in the paper)

Could you provide any insights into these discrepancies and suggest steps I could take to align my results?

Thank you!

**Comment by gaoxiangjun** [comment]
Before releasing the code, I ran the infer and eval once again, the results were the same as the number in the paper.
Did you specify the `--dataset` in the scripts? 
And you may also put the running command in this issue and I will check it.

**Comment by gaoxiangjun** [comment]
Before releasing the code, I ran the infer and eval once again, the results were the same as the number in the paper.
Could you put the running command or other details so that I can check it?

**Comment by zlai0** [comment]
Thanks for your quick reply!

Take kitti as an example, this is the command I used for inference (following the sh files):
python benchmark/infer/infer_batch.py \
    --meta_path ./benchmark/datasets/KITTI.csv \
    --input_rgb_root ./benchmark/datasets/ \
    --saved_root /work/depthcrafter/outputs \
    --saved_dataset_folder results_kitti \
    --process_length 110 \
    --gpu 0 \
    --dataset kitti

and this command for eval: 
python benchmark/eval/eval.py \
    --meta_path ./benchmark/datasets/KITTI.csv \
    --dataset_max_depth 80 \
    --dataset kitti \
    --seq_len 110 \
    --pred_disp_root /work/depthcrafter/outputs/ \
    --gt_disp_root ./benchmark/datasets/

This is the generated ./benchmark/datasets/KITTI.csv file:
filepath_left,filepath_disparity
KITTI/2011_09_30_drive_0016_sync_rgb_left.mp4,KITTI/2011_09_30_drive_0016_sync_disparity.npz
KITTI/2011_09_26_drive_0113_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0113_sync_disparity.npz
KITTI/2011_10_03_drive_0047_sync_rgb_left.mp4,KITTI/2011_10_03_drive_0047_sync_disparity.npz
KITTI/2011_09_26_drive_0020_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0020_sync_disparity.npz
KITTI/2011_09_26_drive_0005_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0005_sync_disparity.npz
KITTI/2011_09_26_drive_0013_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0013_sync_disparity.npz
KITTI/2011_09_26_drive_0036_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0036_sync_disparity.npz
KITTI/2011_09_26_drive_0079_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0079_sync_disparity.npz
KITTI/2011_09_29_drive_0026_sync_rgb_left.mp4,KITTI/2011_09_29_drive_0026_sync_disparity.npz
KITTI/2011_09_26_drive_0095_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0095_sync_disparity.npz
KITTI/2011_09_28_drive_0037_sync_rgb_left.mp4,KITTI/2011_09_28_drive_0037_sync_disparity.npz
KITTI/2011_09_26_drive_0002_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0002_sync_disparity.npz
KITTI/2011_09_26_drive_0023_sync_rgb_left.mp4,KITTI/2011_09_26_drive_0023_sync_disparity.npz

For kitti I am using projected raw LiDaR scans depth and for Sintel I'm using the clean set. I have checked the csv files align with the ones in this repo (except ordering).

Have you changed any setting when running the underlying run.py (e.g. --num-inference-steps, --max-res, --overlap) during inference?

**Comment by gaoxiangjun** [comment]
The run.py is also modified compared with the initial version, did you update it?

**Comment by gaoxiangjun** [comment]
BTW, did you try on scannet or sintel and also get results with deviations?

**Comment by gaoxiangjun** [comment]
What's the GPU and GPU memory you used ?

**Comment by zlai0** [comment]
> @zlai0 The `run.py` and `depthcrafter/utils.py` are also modified compared with the initial version, did you update them?

Yes, I am using the updated version, running with A6000 GPU, memory usage at 28421 MB for a 110-frame video.

The scannet sequences are still rendering. But I just got results on bonn, and it's better than the paper reports, still different though:

abs_relative_difference: 0.068201
rmse_linear: 0.267265
delta1_acc: 0.973856

I was wondering if you can share the prediction npz files you got for any one of the datasets (e.g. KITTI)? I'm looking to see if the issue is with inference or evaluation.

**Comment by gaoxiangjun** [comment]
YEAH Sure.
May I get your email?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zlai0** [comment]
Thanks a lot! My email: zihang.lai@hotmail.com

**Comment by Xiang-cd** [comment]
get more same res with issuer on sintel：
    "name": "ours",
    "abs_relative_difference": 0.3288559830408393,
    "rmse_linear": 6.026657340860642,
    "delta1_acc": 0.6308854202861371,
    "sintel/ambush_5_disparity.npz": [
        0.4074782927483607,
        17.463942768902907,
        0.4360516667366028
    ],

**Comment by Xiang-cd** [comment]
here are my commads:
python benchmark/infer/infer_batch.py \
    --meta_path ./benchmark/csv/meta_sintel.csv \
    --saved_root ${saved_root} \
    --saved_dataset_folder results_sintel \
    --input_rgb_root ${input_rgb_root} \
    --process_length 50 \
    --gpus ${gpus} \
    --dataset sintel
    
    python benchmark/eval/eval.py \                                                                                                                         *[main]
    --meta_path ./benchmark/csv/meta_sintel.csv \
    --dataset_max_depth 70 \
    --dataset sintel \
    --seq_len 50 \
    --pred_disp_root ${pred_disp_root} \
    --gt_disp_root ${gt_disp_root}

**Comment by gaoxiangjun** [comment]
> get more same res with issuer on sintel： "name": "ours", "abs_relative_difference": 0.3288559830408393, "rmse_linear": 6.026657340860642, "delta1_acc": 0.6308854202861371, "sintel/ambush_5_disparity.npz": [ 0.4074782927483607, 17.463942768902907, 0.4360516667366028 ],

what type of GPU do you use?

**Comment by Xiang-cd** [comment]
A800 GPU

**Comment by gaoxiangjun** [comment]
abs_relative_difference: 0.293549
rmse_linear: 6.414517
delta1_acc: 0.696447

I just ran it again on another A100 GPU machine and got the same results as the paper.  After checking the dataset extracting, infer and eval, I think GPU type might be problem  because we train and test both on A100. Could you try on another type of GPU?

**Comment by Xiang-cd** [comment]
I think there is no arch difference on A800 and A100 except nvlink speed. I've run again and I also get my res.
here are entire json file:

```json
{
    "name": "ours",
    "abs_relative_difference": 0.3288553139732118,
    "rmse_linear": 6.026299883627661,
    "delta1_acc": 0.6309564009956692,
    "sintel/ambush_5_disparity.npz": [
        0.40751664228305473,
        17.464326710345567,
        0.4361645579338074
    ],
    "sintel/bamboo_2_disparity.npz": [
        0.19496142864974456,
        2.980593319681541,
        0.7251725792884827
    ],
    "sintel/mountain_1_disparity.npz": [
        0.09283019586362326,
        5.748296681347962,
        0.967109739780426
    ],
    "sintel/bamboo_1_disparity.npz": [
        0.20764244436114251,
        1.6746006748851436,
        0.614038348197937
    ],
    "sintel/shaman_2_disparity.npz": [
        0.1490391957325639,
        0.541831954663643,
        0.8103695511817932
    ],
    "sintel/ambush_6_disparity.npz": [
        0.22485569235450395,
        2.117707258432921,
        0.6050370931625366
    ],
    "sintel/bandage_1_disparity.npz": [
        0.11839318511049371,
        0.19255017628686097,
        0.8426671028137207
    ],
    "sintel/alley_1_disparity.npz": [
        0.1187597110331879,
        3.7437282606178304,
        0.8783725500106812
    ],
    "sintel/temple_3_disparity.npz": [
        0.2624081279956319,
        3.9725281678224293,
        0.5336044430732727
    ],
    "sintel/shaman_3_disparity.npz": [
        0.12051696425662595,
        0.08249596324342448,
        0.8613399267196655
    ],
    "sintel/ambush_2_disparity.npz": [
        1.7142567988474595,
        25.983008108188812,
        0.3922918438911438
    ],
    "sintel/cave_4_disparity.npz": [
        0.368016497432955,
        4.654579102483768,
        0.4213610589504242
    ],
    "sintel/cave_2_disparity.npz": [
        0.5913797223101251,
        16.45021686983184,
        0.1582982838153839
    ],
    "sintel/alley_2_disparity.npz": [
        0.157290002241262,
        3.636243892657276,
        0.7132296562194824
    ],
    "sintel/market_5_disparity.npz": [
        0.5676622147969258,
        3.5106689103919035,
        0.21786001324653625
    ],
    "sintel/sleeping_2_disparity.npz": [
        0.11662073117575764,
        0.3331627022108141,
        0.898398756980896
    ],
    "sintel/ambush_4_disparity.npz": [
        0.2425921042695113,
        1.6039169923123922,
        0.5040878653526306
    ],
    "sintel/sleeping_1_disparity.npz": [
        0.08766677966807349,
        0.08558319266731891,
        0.9393497705459595
    ],
    "sintel/market_6_disparity.npz": [
        0.44499283700703907,
        9.581408962319202,
        0.3353305459022522
    ],
    "sintel/market_2_disparity.npz": [
        0.20992873950520513,
        12.21700432396589,
        0.5714714527130127
    ],
    "sintel/bandage_2_disparity.npz": [
        0.09304210402435276,
        0.15889314262329676,
        0.934319019317627
    ],
    "sintel/ambush_7_disparity.npz": [
        0.077418024966222,
        0.057343158522667026,
        0.981617271900177
    ],
    "sintel/temple_2_disparity.npz": [
        0.9958820774984113,
        21.81420879793368,
        0.17050579190254211
    ]
}
```

is there any mix precision setting or metric setting difference between us?

**Comment by Xiang-cd** [comment]
or is there are errors of downloading?
new download version and old maybe diff?

**Comment by Xiang-cd** [comment]
torch                     2.3.0
torchmetrics              1.4.0.post0
torchvision               0.18.0
diffusers                 0.30.3
transformers              4.44.2

my major lib versions Is here.

**Comment by gaoxiangjun** [comment]
check the requirement.txt. Many libs are different with yours.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Xiang-cd** [comment]
using md5sum on linux
b85f035c682102bcba5c0b1404e3a226  datasets/sintel/alley_1_disparity.npz
b4a3ad78796b3854809e9991dd542695  benchmark/datasets/sintel/alley_1_rgb_left.mp4
does our data match?

**Comment by gaoxiangjun** [comment]
Yeah, the data is matched. You may install the pkg from requirement.txt or try to use some other types of GPU. According to other people's information, the type of GPU may influence the final metric results.
