### ISSUE TITLE
which part of nyuv2

### ISSUE THREAD

**Issue by Xiang-cd** [Tencent/DepthCrafter#27]
there are different source of nyuv2:
- https://huggingface.co/datasets/tanganke/nyuv2
- https://huggingface.co/datasets/sayakpaul/nyu_depth_v2
- https://cs.nyu.edu/~fergus/datasets/nyu_depth_v2.html

which one do you use, and do you have some scripts to process them into a standard format?

**Comment by Xiang-cd** [comment]
oh, i see, only use the test part to do evaluation..

**Comment by Xiang-cd** [comment]
but i still wondering how to do evaluation

**Comment by gaoxiangjun** [comment]
You may see the README and ./benchmark

**Comment by Xiang-cd** [comment]
I think I didn't  find a readme file at ./benchmark dir?

**Comment by gaoxiangjun** [comment]
https://github.com/Tencent/DepthCrafter?tab=readme-ov-file#-dataset-evaluation

**Comment by Xiang-cd** [comment]
$ tree -L 2                                                                                                                                                                                                                                                                       130 ↵                                                                          
.                                                                                                                                                                                                                                                                                                                                                                 
├── download_from_gdrive.py                                                                                                                                                                                                                                                                                                                                       
├── nyu_depth_v2_labeled.mat                                                                                                                                                                                                                                                                                                                                      
├── sync                                                                                                                                                                                                                                                                                                                                                          
│   ├── basement_0001a                                                                                                                                                                                                                                                                                                                                            
│   ├── basement_0001b                                                                                                                                                                                                                                                                                                                                            
│   ├── bathroom_0001                                                                                                                                                                                                                                                                                                                                             
│   ├── bathroom_0002                                                                                                                                                                                                                                                                                                                                             
│   ├── bathroom_0005                                                                                                                                                                                                                                                                                                                                             
│   ├── bathroom_0006                                                                                                                                                                                                                                                                                                                                             
│   ├── bathroom_0007       

thanks, I've readed the readme and the code already, but my downloaded nyuv2 file tree, looks like this, and I could find "path/to/NYUv2/filename_list_test.txt" in my downloaded version, how to align the file tree and file list text file with yours?

**Comment by Xiang-cd** [comment]
thank you for your great work~ wish a help

**Comment by gaoxiangjun** [comment]
filename_list_test.txt is in the dataset. 
[filename_list_test.txt](https://github.com/user-attachments/files/17349236/filename_list_test.txt)

You can also use this.

**Comment by zhizunhu** [comment]
@gaoxiangjun I just got test file from nyu_depth_v2_labeled.mat, RGB image name is same as your filename_list_test.txt，But I only get delta1=0.924，more worse than 0.944 in paper. my gpu is a100-80g. cc @Xiang-cd  Have you reproduced nyuv2 metric? Wish your help, Thanks.
