### ISSUE TITLE
About the output channels of Diffusion U-net?

### ISSUE THREAD

**Issue by 838959823** [Tencent/DepthCrafter#29]
I am unsure about the output channels of the Diffusion U-net and how to control it to generate different depth frames when the output channels are static.

**Comment by wbhu** [comment]
The number of channels for U-Net is 4, while the number for frames can be variable

**Comment by 838959823** [comment]
Thank you for response. It seems that each depth image is conditioned by the corresponding frame, but each frame is processed seperately?

**Comment by wbhu** [comment]
No, there are temporal layers
