### ISSUE TITLE
Making models available on HF

### ISSUE THREAD

**Issue by NielsRogge** [Tencent/DepthCrafter#3]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2409.02095 (feel free to claim the paper so that it appears under your HF account!). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub.

Happy to assist making the models available on the hub once they get released.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. In case the model is a custom PyTorch model, we could probably leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to the model. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work.

## Demo as a Space

One could also create a Gradio demo. Happy to connect with the Gradio folks at HF on making this a breeze.

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by wbhu** [comment]
Hi, 

We now host our model on Hugging Face, https://huggingface.co/tencent/DepthCrafter. But for online demos, it's not so convenient due to its long inference time and HF's time quota for common users. So we only provide a local Gradio demo now.

**Comment by NielsRogge** [comment]
Awesome, thanks for improving its discoverability! 🤗 Will close this issue.
