### ISSUE TITLE
varying depth values

### ISSUE THREAD

**Issue by arlo-ml** [Tencent/DepthCrafter#30]
Hi, Thanks for your amazing work

I've been testing your code with long videos (from 300 to 800 frames). I often get varying values of the background over the time.
For example, with this video (383 frames), I get different values of the background, using these parameters, from frame 231 to frame 315:
Output frame rate: 24
Inference steps: 25
Guidance scale: 1.2
Dataset: kitti

Is it expected with longer videos?

![01](https://github.com/user-attachments/assets/94dd50e2-31d3-48e6-a60e-08b69fc348d7)
![02](https://github.com/user-attachments/assets/fd0d94ea-185e-438d-ac3f-d36e06cc7dde)

**Comment by arlo-ml** [comment]
And this is another scene. Asa you can see, the values of the background change over time:
![01](https://github.com/user-attachments/assets/9aeef267-0572-4fa7-bbb4-37303156c792)
![02](https://github.com/user-attachments/assets/b7976056-6832-45fd-8c1c-5e74d7e9acad)

**Comment by acgourley** [comment]
My understanding of the paper is that they are using a sliding time window and so it makes sense it would shift over periods longer than a couple seconds. I doubt there is a simple fix but I'd love to hear it if people have ideas.

**Comment by wbhu** [comment]
Hi, thank you for your feedback. Due to memory restriction, the max processing length for one time is 110. Videos longer than 110 are processed in overlapped segments. 

Temporal consistency within the same segment is very good, I think. As for temporal consistency among segments, our designed inference strategy (including noise initialization and latent interpolation) works for most cases, but it's hard to always guarantee the consistency among segments due to temporal context.

Best,
Wenbo

**Comment by arlo-ml** [comment]
hi Wenbo, thank you for the explanation
I've already tested around 40 videos (all the sequences are black-and-white films), and I can confirm that your designed inference strategy works for most cases, even with videos longer than 110 frames. I was wondering if using different values for the noise initialization and latent interpolation may help adapting to different scenarios.
I've tried to do a brief search, but I could not find any terminal commands that would help me solving those isolated cases. Would it require to modify your original code?

**Comment by wbhu** [comment]
Hi, the noise initialization for overlapped segments has been included in the code. For the failure case, you may try to set a different random seed (which is default set to 42) by adding the argument "--seed xxx". I'm not sure if this will help or not ...

What will influence for sure is where to segment the video, you may tune this for the failure case

**Comment by arlo-ml** [comment]
Thank you, I'll try to make more tests, following your suggestions

**Comment by STUDYHARD2113** [comment]
> Hi, thank you for your feedback. Due to memory restriction, the max processing length for one time is 110. Videos longer than 110 are processed in overlapped segments.
> 
> Temporal consistency within the same segment is very good, I think. As for temporal consistency among segments, our designed inference strategy (including noise initialization and latent interpolation) works for most cases, but it's hard to always guarantee the consistency among segments due to temporal context.
> 
> Best, Wenbo

hi Wenbo,
I found the code to norm the whole segment depth, if I need to split a very long sequence (>150 frames) into different parts of the infer, if I want to keep the different segments consistent, do I need to remove this part? Because although different parts may have scene overlap, but from the depth gt to consider, then surely the depth range of different segment is not the same?

`# normalize the depth map to [0, 1] across the whole video`
`res = (res - res.min()) / (res.max() - res.min())`

**Comment by wbhu** [comment]
> > Hi, thank you for your feedback. Due to memory restriction, the max processing length for one time is 110. Videos longer than 110 are processed in overlapped segments.
> > Temporal consistency within the same segment is very good, I think. As for temporal consistency among segments, our designed inference strategy (including noise initialization and latent interpolation) works for most cases, but it's hard to always guarantee the consistency among segments due to temporal context.
> > Best, Wenbo
> 
> hi Wenbo, I found the code to norm the whole segment depth, if I need to split a very long sequence (>150 frames) into different parts of the infer, if I want to keep the different segments consistent, do I need to remove this part? Because although different parts may have scene overlap, but from the depth gt to consider, then surely the depth range of different segment is not the same?
> 
> `# normalize the depth map to [0, 1] across the whole video` `res = (res - res.min()) / (res.max() - res.min())`

Hi, thanks for your valuable comments. I think it may produce a little bit better results if the normalization is performed globally. But I'm not sure, since we found the predicted values are almost between [0,1], even without post-normalization. Glad to hear your comments

**Comment by wbhu** [comment]
Closed as no further replies
