### ISSUE TITLE
Benchmarking DepthCrafter vs ML depth pro

### ISSUE THREAD

**Issue by hbardak** [Tencent/DepthCrafter#32]
Hi everyone, 

I am VFX artist and I have a great interest in theses researches. 

I did a quick comparison DepthCrafter and ml depth pro from Apple. 

here my result : 
![Depth_compare_v001 0002](https://github.com/user-attachments/assets/4b4971c2-452d-46b0-918f-88e05ace48df)

I have tested on a video of myself, depth pro isn't consistent over time but the point was to evaluate the quality of the depth map generated by DepthCrafter. I mean by quality id depth data make sense once projected in the 3D world. I had to realign them to be able to compare them. 

1. First of all, I don't have enough VRAM to work at the same resolution than ML_depth pro hence the lack of hair retrieval. 
2. Second the value within the depth data seams to be "distorted" with DepthCrafter. My eyebrow, my eyes, my nose dont' have the correct depth. 
3. Third the shop wall seams to not be straight with DepthCrafter. 

Are there any way to improve point 2 and 3 with the current state of the model?

**Comment by wbhu** [comment]
Thanks for your valuable feedback. 

Point 2&3 are mainly about the "metric depth", while DepthCrafter is currently designed for affine-invariant depth. To convert the affine-invariant depth to metric one, perhaps we need some sparse GT points for aligning the scale and shift and focal length for back-projecting the points

**Comment by hbardak** [comment]
Is it something I can do with the current code to apply your suggestion ? or it needs to be retrained ? 

Would it help if we know the focal length of the used camera ? in my example I know exactly the focal length and the sensor size and thus I can calculate the horizontal/vertical fov.

Real Lens also have some distortion ( barrel or pin cushion ), would it be a good idea to correct the distortion before extracting the depth and reapplying the distortion on the depth ? ( This is pretty trivial to do in the Visual Effects Community )

**Comment by booker-max** [comment]
> Thanks for your valuable feedback.
> 
> Point 2&3 are mainly about the "metric depth", while DepthCrafter is currently designed for affine-invariant depth. To convert the affine-invariant depth to metric one, perhaps we need some sparse GT points for aligning the scale and shift and focal length for back-projecting the points

您好，我手上有稀疏雷达点云的监督，我想要将depthcrafter的结果和metric depth对齐，具体可以怎么做，谢谢

**Comment by hbardak** [comment]
with 1.01 version ( bottom ), much better than 1.0. but still not as good as ml_depth_pro 


![Depth_compare_v002 0002](https://github.com/user-attachments/assets/284e2859-5bcd-4e80-8342-93fbfecfd4a1)

**Comment by wbhu** [comment]
> with 1.01 version ( bottom ), much better than 1.0. but still not as good as ml_depth_pro
> 
> ![Depth_compare_v002 0002](https://private-user-images.githubusercontent.com/26234254/390924128-284e2859-5bcd-4e80-8342-93fbfecfd4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDg4NzcsIm5iZiI6MTczMjg0ODU3NywicGF0aCI6Ii8yNjIzNDI1NC8zOTA5MjQxMjgtMjg0ZTI4NTktNWJjZC00ZTgwLTgzNDItOTNmYmZlY2ZkNGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAyNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNWRkOGMxNWI4NWZjNTE0OGMxOGQzYTk5MDg0ZGQ0MjA2NDA3MmQxMzRmMGViNWM3Yzk3YjRiMjFlOTdiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wCAZowEVkc2n4vgrM5p1SoZ88O7JAe0W40sjUp8bgdY)

Thx for your quick feedback. I think the results are reasonable, as DepthCrafter is designed for affine-invariant depth estimation, a suitable scale, and shift as well as the focal length is required to unproject it to point clouds, while these parameters from DepthPro may not work well with DC's relative depth. Anyway, this test is very informative for depth users
