### ISSUE TITLE
Benchmarking samples

### ISSUE THREAD

**Issue by suhangpro** [Tencent/DepthCrafter#33]
Hi! I see that in the dataset extraction code for benchmarking there are some details in preparing the samples, more specifically:

- The images are cropped, e.g. `img_video[:, 8:-8, 11:-11, :]` in ScanNetv2, `img_video[:, 45:471, 41:601, :]` in NYUv2, etc. 
- Bonn starting and end frames are specified as `start_frame=30, end_frame=140` at one place but `start_frame=0, end_frame=110` as the default function arguments; similarly, KITTI also requires `start_frame` and `end_frame`. 
        
Can I just follow the default values under folder `benchmark/dataset_extract` if I'd like to reproduce and/or compare with the reported numbers? Thanks!

**Comment by gaoxiangjun** [comment]
Yeah sure. These values are the default settings used in our experiments.

**Comment by suhangpro** [comment]
Thanks for confirming!

**Comment by suhangpro** [comment]
Thanks for confirming!
