### ISSUE TITLE
Batch output for single frames

### ISSUE THREAD

**Issue by herrartist** [Tencent/DepthCrafter#34]
How can I batch input/output singe frames from a video to grayscale depthmaps (PNG) on a Windows 10 PC?

**Comment by vitacon** [comment]
I suppose the main point of the question was "how to make DepthCrafter output a sequence of grayscale PNGs instead of a video file".

**Comment by wbhu** [comment]
> I suppose the main point of the question was "how to make DepthCrafter output a sequence of grayscale PNGs instead of a video file".

Thx for clarifying. This is not directly supported currently, but it's quite simple to implement, just modify the saving function would work well.

**Comment by vitacon** [comment]
"It's quite simple" for somebody who already knows Python and numpy. =}

I needed it too and it took me some time  to figure out the types of variables and how to convert them (especially creating 4D array from images to replace read_video_frames). Fortunately, just saving images is really not that complicated.

```
#        save_video(res, save_path + "_depth.mp4", fps=target_fps)
        # save result as separate grayscale images
        for i in range(len(res)):
          frame = res[i]
          frame = frame * 255
          frame = frame.astype(np.uint8)
          im = Image.fromarray(frame)
          im = im.resize((1490, 1080), 1) # upscale back to my original size
          im.save(save_path + '-' + format(i, '03') + '.png')

```

**Comment by vitacon** [comment]
Sorry, I have yet another problem. My hack that reads a sequence of images kind of works but the results look much worse than the original version of run.py.

Original run.py with --max-res 512
![324-král volá za nosítky-20241202-000](https://github.com/user-attachments/assets/b04c3165-ba41-4c9d-8878-b924a32424a4)

run-images.py
![079850](https://github.com/user-attachments/assets/40461ac7-22de-429b-9407-dc9bd4889ab5)

I suppose the problem could lie either in the way I preprocess the images (load image, strip alpha channel, resize it to 512, add it to the 4D numpy array) or in the way I incorporated the DepthCrafter pipeline.

Would you mind taking a look?

**Comment by wbhu** [comment]
It seems the range of "frames_array" passed into ppl is not correct, it should be in [0.0,1.0] as indicated in https://github.com/Tencent/DepthCrafter/blob/main/depthcrafter/depth_crafter_ppl.py#L108

**Comment by vitacon** [comment]
Thanks @wbhu , that was really the problem. =) I supposed some kind of normalization is performed later within the DepthCrafter pipeline and I did not check it.

Now I am wondering what exactly should I normalize.
Either each image before adding it to the array (local normalization)
`img_array = (img_array - img_array.min()) / (img_array.max() - img_array.min())`

or frames_array as a whole (global normalization)
`frames_array = (frames_array - frames_array.min()) / (frames_array.max() - frames_array.min())`

I made a few quick tests and the differences of these two versions are not big but noticeable when I'm switching the resulting images back and forth. However, it's hard to say which option is better. I supposed normalizing the whole array would be better for the overall stability (separate normalization could induce unwanted differences between frames) but it seems the accuracy of both options is slightly different for each frame and even for different objects in the same frame. I guess it also depends on the stability of the input frames.

Local normalization (detail)
![004044_cr](https://github.com/user-attachments/assets/fe65facf-9e9b-4de1-82ca-da89960d59ec)

Global normalization (detail)
![004044g_cr](https://github.com/user-attachments/assets/d1724b8b-1706-4475-aee8-7d4af334a8e1)

What do you think about it? Did you make some exact tests?

**Comment by wbhu** [comment]
Just /255.0 like we done for videos

**Comment by vitacon** [comment]
> Just /255.0 like we done for videos

I see. I tried it at first too but then it occurred to me that real-life videos usually do not include very bright pixels so proper normalization with min and max could get a few more details from the input material.

**Comment by wbhu** [comment]
That's an interesting finding. I guess some video enhancement pre-processing, like histogram equalization, could also improve the details.

**Comment by vitacon** [comment]
BTW I doubt anyone cares but there is a bug in my code above. It seemed to me that glob.glob output is already sorted but it was just a coincidence and sometimes the wrong order made the results very jerky. The list of filenames has to be sorted:

```
# get the list of images
filenames = glob.glob(os.path.join(path_input, "*.png"))
filenames = sorted(filenames)

```

Also, I noticed that adding new images by joining arrays is quite non-economical - especially with 500+ images it becomes very slow. It seems a better way is to allocate the whole array at once 
`frames_array = numpy.empty((framecount, work_height, work_width, 3))`

and just insert the current image at the right place
`frames_array[i] = img_array`
