### ISSUE TITLE
Is possible to increase format size and depth ranger ?

### ISSUE THREAD

**Issue by lucky0511** [Tencent/DepthCrafter#36]
Thank you for the amazing projects!
I have two questions I’d really like to ask:

1/The maximum resolution currently supported is 1024×576 for 26 GB of VRAM. Is it possible to increase this resolution while still consuming around 26 GB of VRAM, even if it processes at a much slower speed?

2/Is it possible to adjust the depth simulation range?

**Comment by wbhu** [comment]
1. Yes! Try to pass "sequential" to the cpu_offload argument, this will save a lot of memory for UNet, with the cost of speed, https://github.com/Tencent/DepthCrafter/blob/main/run.py#L36
2. The generated depth is relative depth, i.e. affine-invariant depth, so I don't think the depth range is an issue.
