### ISSUE TITLE
Is the output depth or disparity?

### ISSUE THREAD

**Issue by MichalGeyer** [Tencent/DepthCrafter#42]
Hi! congrats for the great work!

Could you please clarify if the outputs are depth maps or disparity maps?
I was expecting depth maps but on when I run the model I see high values for near objects and small values for far away objects.
Could you please clarify if there is some post processing that causes this? I saw this in the raw output, not only with the colormap visualizations. What am I missing?

Thanks a lot

**Comment by gaoxiangjun** [comment]
Hi, the output is disparity sequence.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Michal Geyer ***@***.***>
Sent: Sunday, December 8, 2024 6:36:46 PM
To: Tencent/DepthCrafter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Tencent/DepthCrafter] Is the output depth or disparity? (Issue #42)


Hi! congrats for the great work!

Could you please clarify if the outputs are depth maps or disparity maps?
I was expecting depth maps but on when I run the model I see high values for near objects and small values for far away objects.
Could you please clarify if there is some post processing that causes this? I saw this in the raw output, not only with the colormap visualizations. What am I missing?

Thanks a lot
