### ISSUE TITLE
cant run the code token error

### ISSUE THREAD

**Issue by donrikk** [Tencent/DepthCrafter#6]
hey guys, i keep getting an error that says i need my token from huggingface, i go to enter in my token and it wont let me paste it into the field in the prompt it says i can right click to paste it but when i right click it does nothing, when i type it wont let me type and it does nothing, when i press ctrl+V still nothing. i literally cant access the program lol any suggestions.

**Comment by aetherguru** [comment]
1. Download the model and config.json here: https://huggingface.co/tencent/DepthCrafter/tree/main/unet
2. Rename the json file to "config.json" if it has another name after downloading.
3. Put those two files in the project folder: "tencent/DepthCrafter/" (you have to create the folders manually)

**Comment by wbhu** [comment]
> hey guys, i keep getting an error that says i need my token from huggingface, i go to enter in my token and it wont let me paste it into the field in the prompt it says i can right click to paste it but when i right click it does nothing, when i type it wont let me type and it does nothing, when i press ctrl+V still nothing. i literally cant access the program lol any suggestions.

It seems the pasted token won't be displayed for security consideration in HF, but you can direct press enter after pasting

**Comment by wbhu** [comment]
Does it solve your issue?
