### ISSUE TITLE
Depth Map Generation Limitation?

### ISSUE THREAD

**Issue by ietres** [Tencent/DepthCrafter#7]
I have a 27-second video, but the output gives me a 7-second depth map. What am I doing wrong? Is there any limitation on the input regarding the length of frames or seconds?

**Comment by resurgo97** [comment]
What matters is the **number of frames** of the resulting depth map.
I haven't tried, but if you set `--target-fps -1`, you will get the same length of video.

```
parser.add_argument(
        "--target-fps", type=int, default=15, help="Target FPS for the output video"
    )  # -1 for original fps
```

**Comment by wbhu** [comment]
It's strange, the default configuration would subsample the input video at 15 FPS and process the video up to 195 frames, you can tune the "--process-length" arguments for the maximum length, but this also may lead to a longer process time

**Comment by andy500** [comment]
how do l change the process-length" arguments and where is it in your program

**Comment by rider-rebooted** [comment]
I think the real limitation is your GPU video memory

**Comment by acgourley** [comment]
I've noticed an error on a ~60 second 2200x2200px input file:

> Traceback (most recent call last):
>   File "/content/DepthCrafter/run.py", line 201, in <module>
>     depthcrafter_demo.infer(
>   File "/content/DepthCrafter/run.py", line 77, in infer
>     res = self.pipe(
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/DepthCrafter/depthcrafter/depth_crafter_ppl.py", line 162, in __call__
>     video_embeddings = self.encode_video(
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/DepthCrafter/depthcrafter/depth_crafter_ppl.py", line 32, in encode_video
>     video_224 = _resize_with_antialiasing(video.float(), (224, 224))
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 645, in _resize_with_antialiasing
>     input = _gaussian_blur2d(input, ks, sigmas)
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 723, in _gaussian_blur2d
>     out_x = _filter2d(input, kernel_x[..., None, :])
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 684, in _filter2d
>     input = torch.nn.functional.pad(input, padding_shape, mode="reflect")
> RuntimeError: input tensor must fit into 32-bit index math

Do you have advice on how to deal with these? Can I downsample the video? Do I need to break it into shorter chunks?

**Comment by wbhu** [comment]
Hi @acgourley, it seems the tensor is too large to be processed for PyTorch, https://discuss.pytorch.org/t/reflectionpad2d-input-tensor-must-fit-into-32-bit-index-math/111099

Processing 2200x2200 videos would require a lot of memory, if you keep the default arguments (max-resolution), your video will be downsampled into 1024x1024. You may try to make the length shorter or the resolution smaller to fit your hardware

**Comment by acgourley** [comment]
@wbhu Thank you! I ended up solving the problem by adding this env var: PYTORCH_CUDA_ALLOC_CONF='max_split_size_mb:512'

Just changing the input video resolution down didn't seem to solve it, but after adding this, I was able to process those 2200x2200 videos fine.
