### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by resurgo97** [Tencent/DepthCrafter#9]
Hi, I appreciate your work so much, it would be so useful for my personal research.

I tested your code on my 60-frame videos, and it took about 3-5 min to complete.
I guess this makes sense since DepthCrafter is based on (maybe multi-step) denoising technique,
but I want to confirm if if falls in the expected range of runtime. 

Thanks!

**Comment by wbhu** [comment]
What's the GPU type, we reported the inference speed on A100 in README, you may refer to that numbers

**Comment by resurgo97** [comment]
Thanks for your reply!

I ran it on a single RTX 3090.
FPS is around 0.3 FPS, about an order of magnitude slower than yours.
I guess the slowdown is extreme due to the low VRAM size of mine as you mentioned that it requires at least 26GB in README.
Still, I'd love to hear other people's experiences to make sure if it's really the case.

[result]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ffd180be-2ba3-4397-8789-f9622bdd8f28">

[output from nvidia-smi] 
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/ff1d78ee-b03c-416f-a300-1d35724f05ff">

**Comment by wbhu** [comment]
The hi-res inference is about 0.6 fps on A100 as shown in README, so I think 0.3 fps on 3090 is reasonable
